[package]
name = "league_toolkit"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
lib = { version = "0.1.0", path = "../../league-toolkit/crates/league-toolkit", package = "league-toolkit" }
pyo3 = { version = "0.21.2", features = ["extension-module"] }
